### ISSUE TITLE
mac üzerinde python 2.7 ile alınan hata

### ISSUE THREAD

**Issue by danriz** [mehmettaskiner/eksi-sozluk-entry-yedekleyici#8]
merhaba,
kodlamadan pek anlamıyorum. kullanmak istediğimde aşağıdaki hata alındı. 
farklı bir python versiyonu mu kullanılmalı?

işletim sistemi=mac üzerinde 
versiyon=python 2.7

python eksi_entry_yedekleyici.py -h
  File "eksi_entry_yedekleyici.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

> > > pip install -r requirements.txt
> > >   File "<stdin>", line 1
> > >     pip install -r requirements.txt
> > >               ^
> > > SyntaxError: invalid syntax

**Comment by danriz** [comment]
sorun mac üzerinde python çalıştırma ve modül eksikliğiymiş. şöyle çözüldü:
mac 10.11.4 ve python 2.7'de çalışır hale getirmek için ilk olarak projeyi indirirken clone or download linki ile indirmek gerekiyor.
2) 
xcode-select --install

3)
brew install libxml2
brew install libxslt

4)
sudo easy_install pip
sudo pip install lxml

**Comment by mehmettaskiner** [comment]
Selam, aslinda pip install -r requirements.txt yazdiginizda tum gerekli moduller kurulmus olmasi gerekiyordu. Muhtemelen bazi paketler eksikti sizde. Son sozluk guncellemelerinden sonra kontrol edemedim belki su haliyle calismiyor olabilir, hatali gordugunuz bir nokta olursa issue acabilirsiniz.

**Comment by danriz** [comment]
selam,
işletim sistemini yükselttikten sonra moduller ve erişim yetkileri bozulmuş. onları düzelttikten sonra çalıştı. sorun python'u mac üzerinde çalıştırma sorunuydu aslında.
elinize sağlık, çalışıyor.
issue'yu kapattım.
